### ISSUE TITLE
Can't reach web page after remove staging script

### ISSUE THREAD

**Issue by BBBosp** [danb35/freenas-iocage-nextcloud#74] opened 2019-11-05 23:57 UTC
I went through initial setup and everything went well, tested both locally and remotely, was ready to get the let's encrypt cert, ran the remove staging script as suggested because I used the default jail name, and now I can not reach the web page. I thought I got the known bug because I got the following output:

% sudo iocage fstab -l nextcloud
+-------+---------------------------------------------------------------------------------------------------------------------------+
| INDEX |                                                        FSTAB ENTRY                                                        |
+=======+===========================================================================================================================+
| 0     | /mnt/bigdata/portsnap/db        /mnt/bigdata/iocage/jails/nextcloud/root/var/db/portsnap        nullfs  rw      0       0 |
+-------+---------------------------------------------------------------------------------------------------------------------------+
| 1     | /mnt/bigdata/db /mnt/bigdata/iocage/jails/nextcloud/root/var/db/mysql   nullfs  rw      0       0                         |
+-------+---------------------------------------------------------------------------------------------------------------------------+
| 2     | /mnt/bigdata/files      /mnt/bigdata/iocage/jails/nextcloud/root/media/files    nullfs  rw      0       0                 |
+-------+---------------------------------------------------------------------------------------------------------------------------+

but after following the bug fix instructions nothing has changed.

**Comment by Bosstox** [comment] 2019-11-16 11:33
Hi. 

Do you got a solution for this? I got the same issu at 12-6 und 13 Beta.

**Comment by bosp1301** [comment] 2019-11-16 13:33
My solution was to forget about having nextcloud in a jail on freenas and
make a VM with CentOS 7 and run nextcloud 16. Works like a charm and much
higher performance

**Comment by The-Jaeger** [comment] 2019-11-16 21:50
I've got the exact same issue.

"Secure Connection Failed" "PR_END_OF_FILE_ERROR"
"The page you are trying to view cannot be shown because the authenticity of the received data could not be verified.
Please contact the website owners to inform them of this problem."

**Comment by The-Jaeger** [comment] 2019-11-17 19:54
@bosp1301 I tried to do the same thing with Ubuntu with a 500G zvol but it's only detecting the max size as 110 when adding nextcloud as a network drive anywhere else. Did you run into the same issue or was it flawless?

**Comment by bosp1301** [comment] 2019-11-17 20:00
It may be attached to the root partition, not the home partition. Check df

**Comment by The-Jaeger** [comment] 2019-11-17 20:02
@bosp1301 it is attached to the root partition "/". But besides mounting the whole thing elsewhere how do you fix it? It's the only drive on the system besides loop#.

**Comment by bosp1301** [comment] 2019-11-17 20:04
I'm using CentOS right now and removed the entire home partition and
expanded the root partition to fill the drive. Make sure to remove the home
partition from fstab if you go this route because it won't boot otherwise.

**Comment by The-Jaeger** [comment] 2019-11-17 20:11
@bosp1301 so you did this before installing nextcloud? If I did that right now I'd remove everything since I already have it installed. Also, expand the root partition, what do you mean?

**Comment by danb35** [comment] 2019-11-17 20:18
Help me out here--what does the discussion about running Nextcloud in a Linux VM have to do with this script?

**Comment by danb35** [comment] 2019-11-17 20:21
The only thing the script should do is remove one line from `/usr/local/www/Caddyfile`, that line being the one that reads `ca https://acme-staging-v02.api.letsencrypt.org/directory`.  If you're having trouble reaching the Nextcloud web interface after running the `remove-staging` script, see if that line has been removed from the Caddyfile.  If it has, see if Caddy is running (`service caddy status`); if not, try to start it (`service caddy start`).

**Comment by bosp1301** [comment] 2019-11-17 20:26
Nothing, and I apologize if this is the wrong place to have this discussion
with Jaeger, I was just replying with my 2 cents after they asked.

I don't know what went wrong with the script, or my implementation of it
more likely,but I scrapped the idea of having it on nextcloud for my own
sanity and management purposes.

I didn't have the knowledge to troubleshoot it in FreeNAS in the time frame
I had to work on it.

**Comment by The-Jaeger** [comment] 2019-11-17 23:02
@danb35 I've tried to start the caddy service but when loading the page it still responds with "refused to connect" and then when "service caddy status" it states it's not running. After restarting the jail it starts with caddy not running.

Also sorry for discussing irrelevant matters, but it feels like it's impossible to get nextcloud running on Freenas with letsencrypt and I thought it would be another option.

**Comment by The-Jaeger** [comment] 2019-11-17 23:31
SOLUTION: In the Caddyfile, remove "tls { }" it should be a line high up on the file that should just be empty brackets after running remove-staging.sh. Removing these brackets and tls has got it working again.

More specifically: 
nano /usr/local/www/Caddyfile
Find those lines with "tls {" and the closing bracket "}" and delete them. 
Then CTRL+X, press "y" and enter
Then restart caddy "service caddy restart"
Then run "service caddy status" 
If you get "caddy is running as pid ####" then it is working and you should be able to access nextcloud at your domain.

**Comment by danb35** [comment] 2019-11-17 23:34
Thanks, and that explains why I wasn't able to duplicate the issue--I use DNS validation, and that means that stanza of the Caddyfile wouldn't be empty even after the remove-staging script is run.

Now to see if there's a way to make the appropriate changes to both environments by script...

**Comment by The-Jaeger** [comment] 2019-11-17 23:44
I am not proficient at scripting YET, so I wish I could help you. But I can provide you with the configuration I had to reproduce this issue since I ran the script three times isolating variables.

You're an unsung hero for this script, it achieves the impossible. Can't thank you enough. Would love to help in anyway possible.

**Comment by danb35** [comment] 2019-11-18 01:59
I think my last commit to remove-staging.sh should resolve this issue--rather than remove that line, it simply changes the URL to be the production CA.  It's redundant (Caddy will use that URL automatically if it isn't specified), but it avoids the problem with the Caddyfile syntax when there isn't a `dns` directive in the `tls { }` stanza.

**Closed** 2020-04-16 10:41 UTC
